### PR TITLE
Fix WebView2 not getting focus when activating window with alt-tab or…

### PR DESCRIPTION
**Pull request by neil-coretainium**
This should hopefully fix this issue that I raised #96 

I think the issues below from the photino.NET project also relate to this.

https://github.com/tryphotino/photino.NET/issues/77
https://github.com/tryphotino/photino.NET/issues/100

### CODE REVIEW

**Comment by ottodobretsberger** [comment]
Thank you for this contribution. Would you mind elaborating the need for the try-catch block? What are you anticipating going wrong there?
Furthermore, according to the [documentation](https://learn.microsoft.com/en-us/windows/win32/inputdev/wm-activate), MA_NOACTIVATE doesn't seem to be a valid return in this case.

Also, please remove the changes to the test program from the PR.

**Comment by neil-coretainium** [comment]
> Would you mind elaborating the need for the try-catch block? What are you anticipating going wrong there?

On initial app start and first call to the `RegisterFocusInHandler` I get the following exception when trying to send a web message to the photino window.

`System.ApplicationException: 'SendWebMessage cannot be called until after the Photino window is initialized.'`

**Comment by ceee** [comment]
Hi. 
Thanks for your incredible work. 
Do you already know when you are going to create a new release where this fix is implemented?

**Comment by MikeYeager** [comment]
@ceee We will probably publish new versions in early January. We typically let a few stack up and release the changes together every month or so, depending on how critical the changes are and how many we have to publish.

**Pull request merged**
